name: clc-runner-test
shortDescription: DO NOT RUN
author: Matthew Osborn
organization: Matthew Osborn
organizationUrl: http://osbornm.com
version: 0.1.0
updateDate: 5/16/2016
public: false
defaultPlaybook: playbook.yml


fields:
- name: dc
  displayName: datacenter
  type: datacenters  
  required: true
- name: group
  displayName: group
  parent: dc
  required: true
  type: groups
