name: My Product
description: test some stuff
version: 1.0.0
updateDate: May 16, 2016
public: false
author: Matthew Osborn
organization: oscorp
organizationUrl: http://osbornm.com
defaultPlaybook: playbook.yml
tags:
  - OSS

fields:
  - name: datacenter
    displayName: data center
    type: datacenters
    required: true
